### ISSUE TITLE
make build

### ISSUE THREAD

**Issue by X-C0DE** [jbszczepaniak/spotify-cli#11]
>>>make build

```
go mod download
make: go: Command not found
Makefile:5: recipe for target 'install_deps' failed
make: *** [install_deps] Error 127 
```

Can someone help me? I tryied to use a relase in https://github.com/jedruniu/spotify-cli/releases but after configurations and run ./spotify-cli it only open a browser window and nothing more

**Comment by jbszczepaniak** [comment]
Do you have go install on your machine? If you want to install from source you need that one. In terms of release - I will upload one today :)

**Comment by jbszczepaniak** [comment]
I fixed problems reported by users and [released new versions](https://github.com/jbszczepaniak/spotify-cli/releases/tag/v1.0.3)
Please consider using this one, also remember about [requirements](https://github.com/jbszczepaniak/spotify-cli/tree/v1.0.3#prerequisites) for running the project.
I am closing this issue, if running newest release will be still problematic for you - feel free to reopen the issue.

**Comment by X-C0DE** [comment]
For me is not working, and i dont know what i'm doing wrong. This is opened in my terminal but the songs are not playing 

![image](https://user-images.githubusercontent.com/56088454/85296107-4336e380-b477-11ea-9594-d810cbc55963.png)
