### ISSUE TITLE
Could not get token, error: oauth2: cannot fetch token: 400 Bad Request

### ISSUE THREAD

**Issue by gvanbeck** [jbszczepaniak/spotify-cli#7]
Hey

I followed every step of the installationprocess (also provided the localhost:8888 ... uri)
The response then form the localhost is the following

`Could not get token, error: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid authorization code"}`

Any solution?

**Comment by buduboti** [comment]
The same at me.

**Comment by RobatBender** [comment]
:+1:

**Comment by Narong-Kanthnu** [comment]
me too,  Show this error after refresh browser

**Comment by copland** [comment]
You may need to follow the instructions for building from source. I was hitting this issue as well with the latest release but got around it by building from master.

**Comment by jedruniu** [comment]
Are you sure you are setting environment variables? I was just testing this, and still works for me (Ubuntu) both built from sources as well as  when running from release.

Let me do this. I will improve logging a little bit, and we will see where the problem might be. OK?
Also note that you need to have Spotify PREMIUM in order to be able to use this app.

**Comment by jbszczepaniak** [comment]
I fixed problems reported by users and [released new versions](https://github.com/jbszczepaniak/spotify-cli/releases/tag/v1.0.3)
Please consider using this one, also remember about [requirements](https://github.com/jbszczepaniak/spotify-cli/tree/v1.0.3#prerequisites) for running the project.
I am closing this issue, if running newest release will be still problematic for you - feel free to reopen the issue.

**Comment by muniv11111** [comment]
with latest reelease, response from localhost redirect uri: 
"Could not get token, error: spotify: didn't get access code"
