### ISSUE TITLE
Illegal scope

### ISSUE THREAD

**Issue by eduardonunesp** [jbszczepaniak/spotify-cli#8]
When execute `./spotify-cli` it gives an error in browser `Illegal scope`

**Comment by paulojean** [comment]
You can solve that by removing the last two scopes from the url (`+user-read-birthdate+user-read-email`) and redoing the request manually.

**Comment by jbszczepaniak** [comment]
I fixed problems reported by users and [released new versions](https://github.com/jbszczepaniak/spotify-cli/releases/tag/v1.0.3)
Please consider using this one, also remember about [requirements](https://github.com/jbszczepaniak/spotify-cli/tree/v1.0.3#prerequisites) for running the project.
I am closing this issue, if running newest release will be still problematic for you - feel free to reopen the issue.
